dist: xenial
language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
env:
  global:
    - PIPENV_VERBOSITY=-1
install:
  - pipenv install -d --skip-lock
  - pipenv install -d codecov --skip-lock
script:
  - make test-tox
after_success:
  - pipenv run codecov
