# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    environment:
      PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}-{{ .Environment.CACHE_VERSION }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install -d
            pipenv install -d codecov

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}-{{ .Environment.CACHE_VERSION }}

      # run tests!
      - run:
          name: run tests
          command: |
            make test

      - run:
          name: send coverage
          command: |
            pipenv run codecov
